
# https://github.com/jekyll/jekyll/tree/master/lib/site_template
# https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml
# https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/example/_config.yml
# https://gitlab.com/pages/jekyll/blob/master/_config.yml
# https://stackoverflow.com/questions/6856601/how-do-you-create-a-jekyll-site
# 


theme: jekyll-theme-midnight
