
# https://github.com/jekyll/jekyll/tree/master/lib/site_template
# https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml
# https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/example/_config.yml
# https://gitlab.com/pages/jekyll/blob/master/_config.yml
# https://stackoverflow.com/questions/6856601/how-do-you-create-a-jekyll-site
# 



# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sebastien Hillaire

email: spam@spam.com

description: Sebastien Hillaire 3d rendering graphics engineer programming games

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SebHillaire
github_username:  sebh
repository: "https://sebh.github.io/"

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
gems:
  - jekyll-feed

#highlighter: rouge

